name: Build Go App

on:
  push:
    branches: [ "main" ] # 当推送到 main 分支时触发
  workflow_dispatch:     # 允许你在 GitHub 网页上手动点击运行

jobs:
  build:
    runs-on: windows-latest # 强制在 Windows 环境下编译

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # 指定 Go 版本

    - name: Build Executable
      # -ldflags="-H windowsgui" 的作用是隐藏运行时的 CMD 黑框，让程序完全在后台静默运行
      run: go build -ldflags="-H windowsgui" -o GuideListener.exe main.go

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GuideListener-Windows
        path: GuideListener.exe
